Repository WilliamRagstad/IV1201-Project, pull requests merged in 2022-03, with the labels that each got.

#56 Added transactions to all database calls
  recruitment-api/config/DatabaseHandler.ts
  recruitment-api/repository/ApplicationRepository.ts
  recruitment-api/repository/Repository.ts
  recruitment-api/repository/RoleRepository.ts
  recruitment-api/repository/UserRepository.ts
  recruitment-api/service/ApplicationService.ts
  recruitment-api/service/UserService.ts
Labels: feature

#54 Add Data Migration policy
  README.md
Labels: documentation

#53 Authorization and authentication
  recruitment-api/controller/UserController.ts
  recruitment-api/model/User.ts
  recruitment-api/repository/ApplicationRepository.ts
  recruitment-api/service/UserService.ts
  recruitment-app/components/defaultpage.tsx
  recruitment-app/components/header.tsx
  recruitment-app/lib/cookies.ts
  recruitment-app/lib/passhash.ts
  recruitment-app/lib/verification.ts
  recruitment-app/pages/about.tsx
  recruitment-app/pages/application.tsx
  recruitment-app/pages/index.tsx
  recruitment-app/pages/job.tsx
  recruitment-app/pages/login.tsx
  recruitment-app/pages/signup.tsx
  shared/auth/jwt.ts
Labels: enhancement

#62 Minor fixes
  README.md
  recruitment-api/config/DatabaseHandler.ts
  recruitment-api/model/Application.ts
  recruitment-api/model/Availability.ts
  recruitment-api/model/Competence.ts
  recruitment-app/api/counter/[action].ts
  recruitment-app/api/counter/index.ts
  recruitment-app/lib/cookies.ts
  recruitment-app/lib/styles/counter.css
  recruitment-app/lib/useCounter.ts
  recruitment-app/pages/job.tsx
  recruitment-app/pages/signup.tsx
  shared/auth/password_hashing.ts
Labels: fix

#66 API hot fix
  recruitment-api/controller/UserController.ts
  recruitment-app/lib/api.ts
  recruitment-app/pages/signup.tsx
Labels: fix

#65 Signup fix
  recruitment-api/controller/UserController.ts
  recruitment-api/model/SafeUser.ts
  recruitment-app/lib/api.ts
  recruitment-app/pages/signup.tsx
Labels: fix

#67 Test implementation
  .github/workflows/deno.yml
  recruitment-api/tests/ApplicationController.test.ts
  recruitment-api/tests/UserController.test.ts
  recruitment-app/lib/cookies.ts
  recruitment-app/tests/api.test.ts
  recruitment-app/tests/cookies.test.ts
  recruitment-app/tests/passhash.test.ts
  test.bat
Labels: enhancement
