Repository WilliamRagstad/IV1201-Project, pull requests merged in 2022-02, with the labels that each got.

#17 MVC Controller Framework
  recruitment-api/controllers/ExampleController.ts
  recruitment-api/index.ts
  recruitment-api/lib/mvc-manager/ControllerManager.ts
  recruitment-api/lib/mvc-manager/IController.ts
  run.bat
Labels: feature

#18 MVC Controller Utilities and more
  DEVELOPMENT.md
  Recruitment API.postman_collection.json
  recruitment-api/controller/ExampleController.ts
  recruitment-api/controller/UserController.ts
  recruitment-api/controller/index.ts
  recruitment-api/index.ts
  recruitment-api/lib/mvc-manager/ControllerManager.ts
  recruitment-api/lib/mvc-manager/ControllerUtils.ts
  recruitment-api/lib/mvc-manager/IController.ts
  recruitment-api/model/User.ts
Labels: documentation, enhancement, feature

#21 MVC Decorators
  DEVELOPMENT.md
  recruitment-api/controller/ExampleController.ts
  recruitment-api/controller/UserController.ts
  recruitment-api/controller/index.ts
  recruitment-api/index.ts
  recruitment-api/lib/mvc-manager/ControllerManager.ts
  recruitment-api/lib/mvc-manager/ControllerUtils.ts
  recruitment-api/lib/mvc-manager/Decorators.ts
  recruitment-api/lib/mvc-manager/IController.ts
  recruitment-api/lib/mvc-manager/types.ts
  recruitment-api/model/User.ts
Labels: enhancement, feature

#23 Use Knight instead of Controller Manager
  recruitment-api/controller/ExampleController.ts
  recruitment-api/controller/UserController.ts
  recruitment-api/index.ts
  recruitment-api/lib/database-manager/DBHandler.ts
  recruitment-api/lib/mvc-manager/ControllerManager.ts
  recruitment-api/lib/mvc-manager/ControllerUtils.ts
  recruitment-api/lib/mvc-manager/Decorators.ts
  recruitment-api/lib/mvc-manager/IController.ts
  recruitment-api/lib/mvc-manager/types.ts
  recruitment-api/model/CompetenceApplication.ts
  recruitment-api/model/User.ts
Labels: enhancement

#30 Added Documentation
  recruitment-api/lib/database-manager/DBHandler.ts
  recruitment-app/pages/index.tsx
  recruitment-app/pages/job.tsx
  recruitment-app/pages/signup.tsx
Labels: documentation

#35 Added About Us Page
  recruitment-app/pages/about.tsx
  recruitment-app/style/index.css
Labels: feature

#34 Start of Application Viewing Page
  recruitment-app/components/header.tsx
  recruitment-app/pages/application.tsx
Labels: feature

#38 Connected Applications to Backend
  recruitment-api/config/DatabaseHandler.ts
  recruitment-api/controller/ApplicationController.ts
  recruitment-api/index.ts
  recruitment-api/model/Application.ts
  recruitment-api/model/Availability.ts
  recruitment-api/model/Competence.ts
  recruitment-api/model/CompetenceApplication.ts
  recruitment-api/repository/ApplicationRepository.ts
  recruitment-api/service/ApplicationService.ts
  recruitment-app/pages/application.tsx
  recruitment-app/style/index.css
  run.bat
Labels: enhancement

#50 Search for applications
  recruitment-api/controller/ApplicationController.ts
  recruitment-api/model/Application.ts
  recruitment-api/model/Competence.ts
  recruitment-api/model/EmailPassword.ts
  recruitment-api/model/Role.ts
  recruitment-api/model/User.ts
  recruitment-api/repository/ApplicationRepository.ts
  recruitment-app/aleph.config.ts
  recruitment-app/components/header.tsx
  recruitment-app/lib/passhash.ts
  recruitment-app/pages/about.tsx
  recruitment-app/pages/application.tsx
  recruitment-app/pages/index.tsx
  recruitment-app/pages/job.tsx
  recruitment-app/pages/login.tsx
  recruitment-app/pages/signup.tsx
  recruitment-app/style/index.css
Labels: feature
